# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3530bb5ca0997dca894ff938441a16914a215020504c7330fe8e8cf0296afede106682d696e8c0237cbf0f6aa131eb6fd63f1de6fda5bea14fd4f0e0987a6d2

test:
  secret_key_base: 9fa822c410e5d37a541f811baf335d601e4bb3b8f77b1192eda1c6cdf52e16d8c2b6799e5403e22fb8a3b0f7a10b105c35ec56a39c62f546c69a4be1eb01be48

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
